service: goapp
image: dmytro-strukov/goapp

servers:
  web:
    - 192.168.0.1

proxy:
  ssl: false

registry:
  server: ghcr.io
  username: dmytro-strukov
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

